model:
  name: sam
  use_hq: True
  checkpoint: ./ckts/sam_vit_l.pth
  hq_checkpoint: ./ckts/sam_hq_vit_l.pth
  model_type: vit_l 
  device: cuda


data:
  config_file: ./GroundingDINO/groundingdino/config/GroundingDINO_SwinT_OGC.py
  checkpoint_path: ./ckts/groundingdino_swint_ogc.pth
  data_path: ./data/seginw/
  num_select: 100
  num_workers: 1
  device: cuda
  save_json: True
  logging_path: ./logs

  test:
    dataset_type: CocoDataset
    ann_file: ./data/coco/annotations/instances_val2017.json
    img_prefix: ./data/coco/val2017/
    pipeline: test_pipeline

quantization:
  quandecoder: False
  quanrtn: False
  quangptq: False
  quansmooth: False
  quanro: False
  rtn_cuda: False
  gptq_cuda: False
  act_scales_file: ./ckts/sam_vit_lactivation_scales.pt
  act_quant: per_token
  weight_quant: per_channel
  n_bits: 4
  n_bits_mlp: 4
  quantize_output: False
  checkpoint: ./ckts/sam_vit_l.pth
  seed: 42
  output: ./output/hq44k/base_l
  restore_model:  work_dirs/hq_sam_vit_l/epoch_11.pth
  up_down_RTN: none
  qkT_v: True
  channel: False
  percent: 100
  low_high_density: none
  centerQ: False
