model:
  name: sam
  use_hq: True
  checkpoint: ../pretrained_checkpoint/sam_vit_h.pth
  hq_checkpoint: ../pretrained_checkpoint/sam_hq_vit_h.pth
  model_type: vit_h 
  device: cuda


data:
  config_file: ../sam-hq/seginw/GroundingDINO/groundingdino/config/GroundingDINO_SwinB_cfg.py
  checkpoint_path: ../pretrained_checkpoint/groundingdino_swinb_cogcoor.pth
  data_path: ../data/seginw/
  num_select: 300
  num_workers: 4
  device: cuda
  save_json: True


quantization:
  quanrtn: False
  quansmooth: False
  quanro: False
  act_scales_file: ./pretrained_checkpoint/sam_vit_lactivation_scales.pt
  act_quant: per_token
  weight_quant: per_channel
  n_bits: 4
  quantize_output: True


  