model:
  name: sam
  use_hq: True
  checkpoint: ./ckts/sam_vit_l.pth
  # model_type: 'vit_b'
  # hq_checkpoint: './ckts/sam_hq_vit_b.pth'
  model_type: vit_l 
  hq_checkpoint: ./ckts/sam_hq_vit_l.pth
  # model_type: 'vit_h'
  # hq_checkpoint: './ckts/sam_hq_vit_h.pth'
  
  device: cpu


data:
  config_file: ./GroundingDINO/groundingdino/config/GroundingDINO_SwinT_OGC.py
  checkpoint_path: ./ckts/groundingdino_swint_ogc.pth
  data_path: ./data/seginw/
  num_select: 100
  num_workers: 1
  device: cpu
  save_json: True
  logging_path: ./logs

  test:
    dataset_type: CocoDataset
    ann_file: ./data/coco/annotations/instances_val2017.json
    img_prefix: ./data/coco/val2017/
    pipeline: test_pipeline

quantization:
  quandecoder: False
  quanrtn: True
  low_high_density: none
  quangptq: False
  quansmooth: False
  quanro: False
  rtn_cuda: False
  gptq_cuda: False
  act_scales_file: ./ckts/sam_vit_lactivation_scales.pt
  act_quant: per_token
  weight_quant: per_channel
  n_bits: 4
  n_bits_mlp: 16
  quantize_output: False
  up_down_RTN: none
  qkT_v: False
  channel: False
  percent: 100
  centerQ: False
  percent_entropy: 0.5
  percent_entropy_global: 0.7
  high_entropy: True 
  prune_global: True 

