model:
  name: sam
  use_hq: True
  checkpoint: ./pretrained_checkpoint/sam_vit_l.pth
  # model_type: 'vit_b'
  # hq_checkpoint: './ckts/sam_hq_vit_b.pth'
  model_type: vit_l
  hq_checkpoint: ./pretrained_checkpoint/sam_hq_vit_l.pth
  # model_type: vit_h
  # hq_checkpoint: ./pretrained/sam_hq_vit_h.pth
  
  device: cpu
train_prune_rate:
  training_method: diffduo
  learning_rate: 5e-2
  lr_drop_epoch: 2
  start_epoch: 0
  output: './pretrained_checkpoint/prune_rate/'
  max_epoch_num: 12
  batch_size_train: 2
  batch_size_valid: 4
  model_save_fre: 5
  seed: 42
  gpu: [0]
  find_unused_params: True
  world_size: 1
  rank: 0                 
  local_rank: 0           
  distributed: false     
  dist_url: "env://"   
  # training: False 
  # this parameter for duo
  reg_weight: 5
  threshold: 0.00085
  threshold_globle: 0.9999835
  # duo 0.0002 1.000003  diffduo  0.00085 and 0.9999835
data:
  config_file: ./GroundingDINO/groundingdino/config/GroundingDINO_SwinT_OGC.py
  checkpoint_path: ./ckts/groundingdino_swint_ogc.pth
  data_path: ./data/seginw/
  num_select: 100
  num_workers: 1
  device: cpu
  save_json: True
  logging_path: ./logs

  test:
    dataset_type: CocoDataset
    ann_file: ./data/coco/annotations/instances_val2017.json
    img_prefix: ./data/coco/val2017/
    pipeline: test_pipeline

quantization:
  quandecoder: False
  quanrtn: True
  low_high_density: none
  quangptq: False
  quansmooth: False
  quanro: False
  rtn_cuda: False
  gptq_cuda: False
  act_scales_file: ./ckts/sam_vit_lactivation_scales.pt
  act_quant: per_token
  weight_quant: per_channel
  n_bits: 4
  n_bits_mlp: 16
  quantize_output: False
  up_down_RTN: none
  qkT_v: False
  channel: False
  percent: 100
  centerQ: False
  percent_entropy: 1
  percent_entropy_global: 0.5
  high_entropy: True 
  prune_global: True 
  # this parameter for train prune rate
  train_rate_prune: True
  positional_quant: False
  use_percentage: True
