model:
  model_type: vit_b
  checkpoint: ./pretrained_checkpoint/sam_vit_l_0b3195.pth
  seed: 42
  output: ./output/hq44k/base_l
  restore_model:  ./ckts/epoch_11.pth 
  device: cuda
quantization:
  quandecoder: False
  quanrtn: True
  low_high_density: none
  quangptq: False
  quansmooth: False
  quanro: False
  rtn_cuda: False
  gptq_cuda: False
  act_scales_file: ./ckts/sam_vit_lactivation_scales.pt
  act_quant: per_token
  weight_quant: per_channel
  n_bits: 4
  n_bits_mlp: 4
  quantize_output: False
  up_down_RTN: none
  qkT_v: True
  channel: False
  percent: 100
  centerQ: False
  percent_entropy: 0.3
  percent_entropy_global: 0.145
  high_entropy: True 
  prune_global: True 
